In [1]:
#1번
import numpy as np
A = np.array([[1,-2,1],[0,2,-8],[5,0,-5]])
B = np.array([4,8,10])
C = np.linalg.solve(A,B)
print(C)

[ 0.33333333 -2.66666667 -1.66666667]


In [11]:
#2번
#행렬식
import numpy as np
d_array = np.array([[1,3,3],[2,6,9],[-1,1,2]])                
d_array_det = np.linalg.det(d_array)                
print(d_array_det)   

#역행렬
a_array = np.array([[1,3,3],[2,6,9],[-1,1,2]])                
a_array_inv = np.linalg.inv(a_array)                #
print(a_array_inv)  
 

-11.999999999999995
[[-0.25        0.25       -0.75      ]
 [ 1.08333333 -0.41666667  0.25      ]
 [-0.66666667  0.33333333 -0.        ]]


In [12]:
#3번
import numpy as np

vector=np.array([2,3])

unit_vector = vector / np.linalg.norm(vector)
print(unit_vector)

[0.5547002  0.83205029]


In [15]:
#4번

In [28]:
# #5번
import numpy as np
import numpy.linalg as alg

A=np.array([[2,1],[4,3]])
_eigenvalue,_eigenvector=alg.eig(A)
print(_eigenvalue)
print(_eigenvector)


[0.43844719 4.56155281]
[[-0.5392856  -0.36365914]
 [ 0.84212294 -0.93153209]]


In [22]:
#6번
#특이값
from numpy import array
from scipy.linalg import svd
A = array([[3,1], [2,2], [1,3]])
print(A)
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

#특이행렬
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

A = array([[1, 2], [3, 4], [5, 6]])
print(A)

U, s, VT = svd(A)

Sigma = zeros((A.shape[0], A.shape[1]))

Sigma[:A.shape[1], :A.shape[1]] = diag(s)
B = U.dot(Sigma.dot(VT))
print(B)
 

[[3 1]
 [2 2]
 [1 3]]
[[-5.77350269e-01  7.07106781e-01  4.08248290e-01]
 [-5.77350269e-01  2.01032697e-16 -8.16496581e-01]
 [-5.77350269e-01 -7.07106781e-01  4.08248290e-01]]
[4.89897949 2.        ]
[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]
[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [23]:
#7번
from sympy import *
m=Matrix([[1,3,3,2], [2,6,9,7],[-1,1,2,4]])
print(m.nullspace())
[]



[Matrix([
[ 7/4],
[-1/4],
[  -1],
[   1]])]


[]